### Тема “Вычисления с помощью Numpy”
Задание 1

In [4]:
import numpy as np

In [23]:
x1 = [1, 2, 3, 3, 1]

In [25]:
x2 = [6, 8, 11, 10, 7]

In [29]:
f = np.array([x1,x2])

In [36]:
a = f.transpose()


In [46]:
mean_a = a.mean(axis = 0 )
mean_a

array([2. , 8.4])

Задание 2

In [42]:
a_centered = a - mean_a

In [43]:
a_centered



array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [59]:
z1 = a_centered[:, 0]

In [60]:
z2 = a_centered[:, -1]

In [62]:
a_centered_sp = z1 @ z2
a_centered_sp

8.0

In [64]:
N = a.shape[0]
N

5

In [66]:
M = a_centered_sp/ (N - 1)
M

2.0

Задание 4

In [68]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [67]:
m = np.cov(a.transpose())
m

array([[1. , 2. ],
       [2. , 4.3]])

### Тема “Работа с данными в Pandas”

Задание 1

In [69]:
import pandas as pd